version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/my-app/
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
